# Generated by Django 3.2.5 on 2021-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('vetement', 'Vêtement'), ('masque', 'Masque')], default='vetement', max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('prix', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='club/images/shop/')),
                ('url', models.URLField(max_length=150)),
            ],
        ),
    ]
