# Generated by Django 3.2.5 on 2021-11-02 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('points', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('11', 'Équipe à 11'), ('7A', 'Équipe à 7 A'), ('7B', 'Équipe à 7 B'), ('ancien', 'Les anciens membres')], max_length=30)),
                ('points', models.IntegerField(default='0')),
                ('logo', models.ImageField(blank=True, upload_to='club/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant'), ('ancien', 'Ancien membre')], max_length=30)),
                ('poste', models.CharField(choices=[('gardien', 'Gardien'), ('def', 'Défenseur'), ('lat', 'Latéral'), ('mdef', 'Milieu Défensif'), ('moff', 'Milieu offensif'), ('ailier', 'Ailier'), ('attaquant', 'Attaquant'), ('arbitre', 'Arbitre'), ('entraineur', 'Entraineur')], max_length=50)),
                ('num_maillot', models.SmallIntegerField()),
                ('anciennete', models.DateField(blank=True, null=True)),
                ('tel', models.IntegerField()),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('ville', models.CharField(max_length=50)),
                ('num_licence', models.IntegerField()),
                ('licence_is_paid', models.BooleanField(default=False)),
                ('certif_medical', models.BooleanField(default=False)),
                ('reglement', models.BooleanField(default=False)),
                ('photo_face', models.ImageField(blank=True, upload_to='club/images/')),
                ('photo_dos', models.ImageField(blank=True, upload_to='club/images/')),
                ('equipe', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journee', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=60)),
                ('domicile', models.BooleanField(default=False)),
                ('score_fcpoto', models.IntegerField(default='0')),
                ('score_adversaire', models.IntegerField(default='0')),
                ('enjeu', models.CharField(choices=[('championnat', 'Championnat'), ('coupe', 'Coupe')], default='championnat', max_length=30)),
                ('adversaire', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.adversaire')),
                ('equipe', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
                ('saison', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.saison')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('lien', models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant')], max_length=30)),
                ('profil', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('entreprise', models.CharField(max_length=30)),
                ('entreprise_is_sponsor', models.BooleanField(default=False)),
                ('logo_entreprise', models.ImageField(blank=True, upload_to='club/images/')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('vie_club', 'Vie du club'), ('evenement', 'Événement'), ('sortie', 'Sortie')], default='vie_club', max_length=30)),
                ('titre', models.CharField(max_length=40)),
                ('contenu', models.TextField(max_length=4000)),
                ('photo', models.ImageField(blank=True, upload_to='club/images/blog/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
        migrations.AddField(
            model_name='adversaire',
            name='equipe',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.equipe'),
        ),
        migrations.AddField(
            model_name='adversaire',
            name='saison',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.saison'),
        ),
    ]
