# Generated by Django 3.2.5 on 2021-09-21 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('11', 'Équipe à 11'), ('7A', 'Équipe à 7 A'), ('7B', 'Équipe à 7 B')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant')], max_length=30)),
                ('poste', models.CharField(choices=[('gardien', 'Gardien'), ('def', 'Défenseur'), ('lat', 'Latéral'), ('mdef', 'Milieu Défensif'), ('moff', 'Milieu offensif'), ('ailier', 'Ailier'), ('attaquant', 'Attaquant'), ('arbitre', 'Arbitre')], max_length=50)),
                ('num_maillot', models.SmallIntegerField()),
                ('tel', models.IntegerField()),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('ville', models.CharField(max_length=50)),
                ('num_licence', models.IntegerField()),
                ('licence_is_paid', models.BooleanField(default=False)),
                ('certif_medical', models.BooleanField(default=False)),
                ('reglement', models.BooleanField(default=False)),
                ('photo_face', models.ImageField(blank=True, upload_to='club/images/')),
                ('photo_dos', models.ImageField(blank=True, upload_to='club/images/')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journee', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=60)),
                ('adversaire', models.CharField(max_length=40)),
                ('domicile', models.BooleanField(default=False)),
                ('enjeu', models.CharField(choices=[('championnat', 'Championnat'), ('coupe', 'Coupe')], default='championnat', max_length=30)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('lien', models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant')], max_length=30)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=30)),
                ('entreprise_is_sponsor', models.BooleanField(default=False)),
                ('logo_entreprise', models.ImageField(blank=True, upload_to='club/images/')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
    ]
