# Generated by Django 3.2.5 on 2021-09-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant')], max_length=30)),
                ('poste', models.CharField(choices=[('gardien', 'Gardien'), ('def', 'Défenseur'), ('lat', 'Latéral'), ('mdef', 'Milieu Défensif'), ('moff', 'Milieu offensif'), ('ailier', 'Ailier'), ('attaquant', 'Attaquant'), ('arbitre', 'Arbitre')], max_length=50)),
                ('num_maillot', models.SmallIntegerField()),
                ('tel', models.IntegerField()),
                ('date_naissance', models.DateField(null=True)),
                ('adresse', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('ville', models.CharField(max_length=50)),
                ('num_licence', models.IntegerField()),
                ('licence_is_paid', models.BooleanField(default=False)),
                ('certif_medical', models.BooleanField(default=False)),
                ('reglement', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
