# Generated by Django 3.2.5 on 2021-11-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='famille',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='match',
            name='adversaire',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='match',
            name='saison',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Adversaire',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Emploi',
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
        migrations.DeleteModel(
            name='Famille',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.DeleteModel(
            name='Saison',
        ),
    ]
