# Generated by Django 3.2.5 on 2021-09-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='equipe',
            field=models.CharField(choices=[('11', 'Équipe à 11'), ('7A', 'Équipe à 7 A'), ('7B', 'Équipe à 7 B'), ('ancien', 'Les anciens membres')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profil',
            name='statut',
            field=models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant'), ('ancien', 'Ancien membre')], max_length=30),
        ),
    ]
