# Generated by Django 3.2.5 on 2021-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210924_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='anciennete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
