# Generated by Django 3.2.5 on 2021-09-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=30)),
                ('entreprise_is_sponsor', models.BooleanField(default=False)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
    ]
