# Generated by Django 3.2.5 on 2021-09-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_emploi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField(null=True)),
                ('lien', models.CharField(choices=[('joueur', 'Joueur'), ('dirigeant', 'Dirigeant')], max_length=30)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.profil')),
            ],
        ),
    ]
