# Generated by Django 3.2.5 on 2021-09-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_emploi_equipe_famille_match_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='points',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='Adversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('points', models.IntegerField(default='0')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='adversaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.adversaire'),
        ),
    ]
