# Generated by Django 3.2.5 on 2021-09-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_famille'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('11', 'Équipe à 11'), ('7A', 'Équipe à 7 A'), ('7B', 'Équipe à 7 B')], max_length=30)),
            ],
        ),
    ]
