# Generated by Django 3.2.5 on 2021-09-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.equipe'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.profil'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journee', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=60)),
                ('adversaire', models.CharField(max_length=40)),
                ('domicile', models.BooleanField(default=False)),
                ('enjeu', models.CharField(choices=[('championnat', 'Championnat'), ('coupe', 'Coupe')], default='championnat', max_length=30)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
            ],
        ),
    ]
