# Generated by Django 3.2.5 on 2021-09-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20210928_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversaire',
            name='saison',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.saisons'),
        ),
        migrations.AlterField(
            model_name='match',
            name='saison',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.saisons'),
        ),
    ]
