# Generated by Django 3.2.5 on 2021-09-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saisons',
            new_name='Saison',
        ),
    ]
