# Generated by Django 3.2.5 on 2021-09-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_rename_saisons_saison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='adversaire',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='match',
            name='saison',
        ),
        migrations.DeleteModel(
            name='Adversaire',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Saison',
        ),
    ]
