# Generated by Django 3.2.5 on 2021-09-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20210929_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('points', models.IntegerField(default='0')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journee', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=60)),
                ('domicile', models.BooleanField(default=False)),
                ('enjeu', models.CharField(choices=[('championnat', 'Championnat'), ('coupe', 'Coupe')], default='championnat', max_length=30)),
                ('adversaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.adversaire')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipe')),
                ('saison', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.saison')),
            ],
        ),
        migrations.AddField(
            model_name='adversaire',
            name='saison',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.saison'),
        ),
    ]
