# Generated by Django 3.2.5 on 2021-10-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20210929_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='logo',
            field=models.ImageField(blank=True, upload_to='club/images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_adversaire',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_fcpoto',
            field=models.IntegerField(default='0'),
        ),
    ]
