# Generated by Django 3.2.5 on 2021-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_auto_20211004_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
