# Generated by Django 3.2.5 on 2021-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenu',
            field=models.TextField(max_length=4000),
        ),
    ]
