# Generated by Django 3.2.5 on 2021-10-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=8, max_digits=19)),
                ('value', models.DecimalField(decimal_places=8, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_trans', models.CharField(choices=[('entree', 'Entrée'), ('depense', 'Dépense')], max_length=10)),
                ('categorie', models.CharField(choices=[('licence', 'Licence'), ('Sponsor', 'Sponsor'), ('Don', 'Don'), ('Materiel', 'Matériel'), ('Arbitre', 'Arbitre'), ('Assurances', 'Assurances'), ('Collation', 'Collation'), ('Remboursement', 'Remboursement')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=8, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresorerie.compte')),
            ],
        ),
    ]
