# Generated by Django 3.2.5 on 2021-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='value',
        ),
        migrations.AddField(
            model_name='compte',
            name='montant_initial',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19),
        ),
        migrations.AlterField(
            model_name='compte',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
