# Generated by Django 3.2.5 on 2021-10-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0002_auto_20211015_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remboursement',
            field=models.CharField(default='', max_length=30, verbose_name='Personne à rembourser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_trans',
            field=models.CharField(choices=[('entree', 'Entrée'), ('depense', 'Dépense')], max_length=10, verbose_name='Type de transaction'),
        ),
    ]
