# Generated by Django 3.2.5 on 2021-10-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0003_auto_20211025_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='nom',
            field=models.CharField(default='', max_length=30),
        ),
    ]
